experiment_config:

  categories:
    rctype: ['depthpointwise', 'pointdepthwise', 'self', 'full'] #, 'local', 'localdepthwise']
    rctarget: ['output', 'input', 'middle']  # Target for recurrent connections
    pattern: ['01110', '11100', '1']
    dsteps: [20]
    dt: [2]
    tau: [7, 9, 11, 13]
    tff: [0, 10]
    trc: [4, 6, 8, 10]
    lossrt: [0, 20, 40, 60, 80, 90, 98]

  response:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 20
      intro: 0
      stim: [16]

  responseffonly:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 20
      intro: 0
      stim: [16]
      ffonly: 'true'

  stability:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      dsteps: 200
      stim: [100]

  duration:
    status: trained
    parameter: stim
    data_loader: StimulusDuration
    data_args:
      # dsteps: 20
      # stim: [1,2,3,4,6,8,10,12,14,16]
      dsteps: 60
      intro: 2
      stim: [2,4,6,8,10,20,30,40,50]

  contrast:
    status: trained
    parameter: contrast
    data_loader: StimulusContrast
    data_args:
      dsteps: 100
      stim: 15
      contrast: [0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0]  

  interval:
    status: trained
    parameter: interval
    data_loader: StimulusInterval
    data_args:
      dsteps: 50
      stim: 5
      interval: [2, 5, 10]

  noise_adaption:
    status: trained
    parameter: noise
    data_loader: NoiseAdaption
    data_args:
      dsteps: 30
      tadapt: [5, 10, 20]
      tdelay: [1, 2, 5]
      ttest: 5
      noise: ["none", "same", "different"]

  spatialsplit:
    status: trained
    parameter: topdown
    data_loader: DoubleStimulus
    data_args:
      topdown: [False]